// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxWxMRLmd263lTgkjE3Tugn061Is_vH8A',
    appId: '1:1063645699274:web:6457cf18d00e82decfe833',
    messagingSenderId: '1063645699274',
    projectId: 'zupurb-dev',
    authDomain: 'zupurb-dev.firebaseapp.com',
    storageBucket: 'zupurb-dev.firebasestorage.app',
    measurementId: 'G-FQQJQ5EG0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUrv8pDykIFORoqpm9DdYzb_t3fcdAl_c',
    appId: '1:1063645699274:android:fbb70bfa649c156fcfe833',
    messagingSenderId: '1063645699274',
    projectId: 'zupurb-dev',
    storageBucket: 'zupurb-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGDy_sKAsaDffZt37psBbRfV9CcJ_zw8E',
    appId: '1:1063645699274:ios:2096e2942f14ff16cfe833',
    messagingSenderId: '1063645699274',
    projectId: 'zupurb-dev',
    storageBucket: 'zupurb-dev.firebasestorage.app',
    iosBundleId: 'com.zupurb.zupurbApp',
  );
}
