// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoGnMQGysi8AUq6SyWLs0n-H39ddl7u74',
    appId: '1:122627565692:web:43a54f108565b8274481f9',
    messagingSenderId: '122627565692',
    projectId: 'zupurb-9580f',
    authDomain: 'zupurb-9580f.firebaseapp.com',
    storageBucket: 'zupurb-9580f.firebasestorage.app',
    measurementId: 'G-PTKV2VQ85E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10NSH2hxAbrMXoYcK_b00GA1pV3ORj-o',
    appId: '1:122627565692:android:7b23de7b8d7d958b4481f9',
    messagingSenderId: '122627565692',
    projectId: 'zupurb-9580f',
    storageBucket: 'zupurb-9580f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOt_SQTUueqCGLKz4YNlYcIyU9wtmT0p0',
    appId: '1:122627565692:ios:9a88c8e2fb69f5464481f9',
    messagingSenderId: '122627565692',
    projectId: 'zupurb-9580f',
    storageBucket: 'zupurb-9580f.firebasestorage.app',
    iosBundleId: 'com.zupurb.zupurbApp',
  );
}
